name: Neovim Plugin Tests

on:
  push:
    branches:
      - main
      - feat/* # Adjust for your branch patterns
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Neovim
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:neovim-ppa/stable -y
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Run Tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh
