name: Neovim Plugin Tests

on:
  push:
    branches:
      - main
      - feat/* # Adjust as needed for your branch patterns
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim git
          git clone https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/lazy/plenary.nvim

      - name: Run Tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh
